### ISSUE TITLE
Run rake spec error

### ISSUE THREAD

**Issue by orangeagain** [bitquery/activecube#15]
spec/spec_helper.rb config:
```
ActiveRecord::Base.configurations = HashWithIndifferentAccess.new(
    default: {
      adapter: 'clickhouse',
      host: 'localhost',
      port: 8123,
      database: 'test',
      username: 'default',
      password: nil
    }
  )

  ActiveRecord::Base.establish_connection(:default)
end
```
run "sudo rake spec"
return error:
```
Failures:

  1) Activecube context executes in context
     Failure/Error: ActiveRecord::MigrationContext.new(MIGRATIONS_PATH, ActiveRecord::Base.connection.schema_migration).up
     
     ArgumentError:
       wrong number of arguments (given 3, expected 2)
     # /var/lib/gems/3.0.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:260:in `initialize'
     # /var/lib/gems/3.0.0/bundler/gems/clickhouse-activerecord-7d638fee3548/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:95:in `new'
     # /var/lib/gems/3.0.0/bundler/gems/clickhouse-activerecord-7d638fee3548/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:95:in `create_table_definition'
     # /var/lib/gems/3.0.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:295:in `create_table'
     # /var/lib/gems/3.0.0/gems/activerecord-6.0.2.1/lib/active_record/schema_migration.rb:33:in `create_table'
     # /var/lib/gems/3.0.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1206:in `initialize'
     # /var/lib/gems/3.0.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1061:in `new'
     # /var/lib/gems/3.0.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:1061:in `up'
     # ./spec/cases/activecube_spec.rb:3:in `block (2 levels) in <top (required)>'

```
